export function usageText(): string {
  return [
    "Usage:",
    "  bun brave-search/index.ts web-search [options] <query>",
    "  bun brave-search/index.ts llm-context [options] <query>",
    "",
    "Auth:",
    "  Add BRAVE_SEARCH_API_KEY=<your-key> to toolbelt/.env",
    "",
    "Common options:",
    "  --count <n>            Result count",
    "  --country <code>       Country code, e.g. US",
    "  --search-lang <lang>   Search language, e.g. en",
    "  --freshness <value>    pd | pw | pm | py | YYYY-MM-DDtoYYYY-MM-DD",
    "",
    "web-search options:",
    "  --offset <n>           Result offset",
    "  --safesearch <mode>    off | moderate | strict",
    "",
    "llm-context options:",
    "  --max-urls <n>                 Maximum URLs",
    "  --max-tokens <n>               Maximum token budget",
    "  --max-snippets <n>             Maximum snippets across all URLs",
    "  --max-tokens-per-url <n>       Maximum tokens per URL",
    "  --max-snippets-per-url <n>     Maximum snippets per URL",
    "  --threshold <mode>             strict | balanced | lenient | disabled",
    "  --enable-local <true|false>    Force local recall behavior",
    "",
    "Examples:",
    '  bun brave-search/index.ts web-search --count 5 "best Bun TypeScript testing patterns"',
    '  bun brave-search/index.ts llm-context --max-tokens 2048 --threshold strict "React hooks best practices"',
    "",
    "See brave-search.AGENTS.md in this package for full documentation.",
  ].join("\n");
}
